# Generated by Django 4.2.19 on 2025-02-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default_product.png', upload_to='products/', verbose_name='商品图片'),
        ),
    ]
